apiVersion: apps/v1
kind: Deployment
metadata:
  name: chicken-api
  namespace: chicken-dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: chicken-api
  template:
    metadata:
      labels:
        app: chicken-api
    spec:
      containers:
        - name: chicken-api
          image: chicken-api:local
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "dev"
          volumeMounts:
            - mountPath: /app/output
              name: model-storage
      volumes:
        - name: model-storage
          emptyDir: {}
