apiVersion: v1
kind: Service
metadata:
  name: chicken-api-service
  namespace: chicken-dev
spec:
  selector:
    app: chicken-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Choisi manuellement
